### ISSUE TITLE
No treated_train/test.csv for USCensus1990/HumanActivityRecognition/ForestCoverType datasets for Clustering.py

### ISSUE THREAD

**Issue by SachinLearns** [TabularNCD/ICDM2022#1]
I tried running Clustering.py for various datasets. It is not working for the mentioned three datasets.

`python Clustering.py --dataset_name ForestCoverType --method kmeans --n_runs 5`

> INFO:root:Importing ForestCoverType...
Traceback (most recent call last):
  File "Clustering.py", line 88, in <module>
    x_train, y_train, x_unlab, y_unlab, x_test, y_test, x_full, y_full, y_full_classifier, y_train_classifier, y_test_classifier, grouped_unknown_class_val, classifier_mapping_dict, cat_columns_indexes = import_dataset_with_name(args.dataset_name, device)
  File "/TabularNCD/src/import_utils.py", line 47, in import_dataset_with_name
    x_train, y_train, x_unlab, y_unlab, x_test, y_test = import_split_dataset('./data/' + dataset_name + '/', device, n_unknown_classes=n_unknown_classes)
  File "/TabularNCD/src/import_utils.py", line 239, in import_split_dataset
    train_df = pd.read_csv(dataset_folder_path + 'treated_train.csv')
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/anaconda3/envs/NCD/lib/python3.8/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/ForestCoverType/treated_train.csv'

Similar errors for USCensus1990 and HumanActivityRecognition datasets.

`python Clustering.py --dataset_name HumanActivityRecognition --method kmeans --n_runs 5`

`python Clustering.py --dataset_name USCensus1990 --method kmeans --n_runs 5`

All other datasets are working in the desired manner. 
Kindly suggest.

**Comment by ColinTr** [comment]
Hi, thanks for your interest in TabularNCD.

These datasets are too large to upload to GitHub, so I cannot add them here.
You are free to experiment with your own datasets though.

Best regards.
